"use client";
import { Chip, Image } from "@nextui-org/react";
import { Card } from "@nextui-org/card";
import { Icon } from "@iconify/react";

export function CompanyOverview() {
  return (
    <Card
      className="rounded-lg flex items-center justify-center border p-5"
      shadow="none"
    >
      <div className=" grid md:grid-cols-[max-content_auto] place-items-center gap-5">
        <Image
          width={100}
          radius="full"
          src="https://nextui.org/images/album-cover.png"
          alt="NextUI Album Cover"
          className="h-max"
        />
        <div>
          <div className="flex flex-col text-center items-center md:flex-row md:items-start md:text-start gap-4">
            <div>
              <h2 className="text-xl font-semibold leading-none">Parsin Exchange</h2>
              <h4 className="text-base text-muted-foreground">
                Financial Industry
              </h4>
            </div>
            <Chip startContent={<Icon icon="mingcute:ai-line" />} radius="lg">
              Content Generated by AI
            </Chip>
          </div>
          <article>
            <div className="flex flex-row space-x-5 items-center"></div>
            <p className="mt-4 text-sm text-muted-foreground">
              Binance Holdings Ltd., branded Binance, is a global company that
              operates the largest cryptocurrency exchange in terms of daily
              trading volume of cryptocurrencies. Binance was founded in 2017 by
              Changpeng Zhao, a developer who had previously created
              high-frequency trading software cryptocurrencies. Binance was
              founded in 2017 by Changpeng Zhao, a developer who had previously
              created high-frequency trading software...
            </p>
          </article>
        </div>
      </div>
    </Card>
  );
}
