"use client";
import { Chip, Image } from "@nextui-org/react";
import { Card } from "@nextui-org/card";
import { Icon } from "@iconify/react";
import { Business } from "@/types/dataTypes";
import { DictsTypes } from "@/app/[lang]/dictionaries/dictionaries";

export function CompanyOverview({
  exchangeData,
  dicts,
}: {
  exchangeData: Business ;
  dicts: DictsTypes;
}) {
  return (
    <Card
      className="rounded-lg flex items-center justify-center border p-5"
      shadow="none"
    >
      <div className=" grid md:grid-cols-[max-content_auto] place-items-center gap-5">
        <Image
          width={100}
          radius="full"
          src="https://nextui.org/images/album-cover.png"
          alt="NextUI Album Cover"
          className="h-max"
        />
        <div>
          <div className="flex flex-col text-center items-center md:flex-row md:items-start md:text-start gap-4">
            <div>
              <h2 className="text-xl font-semibold leading-none">{exchangeData?.name?.[dicts?.lang as keyof typeof exchangeData.name?? "fa"] || "No name available"}</h2>
              <h4 className="text-base text-muted-foreground">
              {exchangeData?.industry}
              </h4>
            </div>
            <Chip startContent={<Icon icon="mingcute:ai-line" />} radius="lg">
              Content Generated by AI
            </Chip>
          </div>
          <article>
            <div className="flex flex-row space-x-5 items-center"></div>
            <p className="mt-4 text-sm text-muted-foreground"> {exchangeData?.description?.[dicts?.lang as keyof typeof exchangeData.description] || "No description available"}
            </p>
          </article>
        </div>
      </div>
    </Card>
  );
}
