"use client";
import { Card } from "@nextui-org/card";
import { Business } from "@/types/dataTypes";
import { DictsTypes } from "@/app/[lang]/dictionaries/dictionaries";
import img1 from '@/public/image.png'
import Image from "next/image";
export function CompanyOverview({
  exchangeData,
  dicts,
}: {
  exchangeData: Business;
  dicts: DictsTypes;
}) {
  return (
    <Card
      className="flex lg:items-start justify-center border p-4 py-8"
      shadow="none"
    >
      <div className=" grid md:grid-cols-[max-content_auto] place-items-center gap-8 mx-4">
        <Image
          src={img1}
          width={130}
          alt="NextUI Album Cover"
          className="rounded-full object-cover aspect-square"
        />
        <div>
          <div className="flex flex-col text-center items-center md:flex-row md:items-start md:text-start gap-2">
            <div>
              <h2 className="text-xl font-semibold leading-none">
                {exchangeData?.name?.[
                  (dicts?.lang as keyof typeof exchangeData.name) ?? "en"
                ] || "No name available"}
              </h2>
              {exchangeData?.tags?.map((e,index) => (
                <h4 className="text-base text-muted-foreground" key={index}>{e?.[dicts?.lang]}</h4>
              ))}
            </div>
            {/* <Chip startContent={<Icon icon="mingcute:ai-line" />} radius="lg">
              Content Generated by AI
            </Chip> */}
          </div>
          <article>
            <div className="flex flex-row space-x-5 items-center"></div>
            <p className="mt-4 text-sm text-muted-foreground">
              {" "}
              {exchangeData?.description?.[
                dicts?.lang as keyof typeof exchangeData.description
              ] || "No description available"}
            </p>
          </article>
        </div>
      </div>
    </Card>
  );
}
